// Human-readable labels for the feature keys in server/features.js's
// FEATURES catalog — kept in one place so SubscriptionCard, UpgradeModal,
// and FeatureLock all describe the same flag the same way.
export const FEATURE_LABELS: Record<string, string> = {
  featuredPlacement: "Featured placement",
  priorityRanking: "Priority ranking in Discovery",
  featuredOrganizerBadge: "Featured organizer badge",
  homepageRecommendations: "Homepage recommendations",
  advancedAnalytics: "Advanced analytics",
  ticketClickTracking: "Ticket click tracking",
  conversionTracking: "Conversion tracking",
  trafficSources: "Traffic sources",
  audienceInsights: "Audience insights",
  eventComparisonReports: "Event comparison reports",
  promoCodes: "Promo codes",
  discountCampaigns: "Discount campaigns",
  earlyBirdCampaigns: "Early-bird campaigns",
  scheduledAnnouncements: "Scheduled announcements",
  bulkNotifications: "Bulk notifications to attendees",
  teamMembers: "Team members",
  staffPermissions: "Staff permissions",
  eventTemplates: "Event templates",
  recurringEvents: "Recurring events",
  waitlists: "Waitlists",
  advancedAttendanceReports: "Advanced attendance reports",
  csvExports: "CSV exports",
  advancedCheckInAnalytics: "Advanced check-in analytics",
  customOrganizerThemes: "Custom organizer themes",
  customEventThemes: "Custom event themes",
  customUrls: "Custom URLs",
  customBranding: "Custom branding",
  reducedWeynBranding: "Reduced Weyn branding",
  aiStudio: "AI Studio",
  eventWorkflows: "Event workflows",
  adCopyGeneration: "Ad copy generation",
  utmLinkBuilder: "UTM link builder",
  referralPrograms: "Referral programs",
  marketingCalendar: "Marketing calendar",
  brandKit: "Brand kit",
};
