// Dev-only mock events. Used ONLY as a fallback when the events API is
// unreachable or returns nothing AND import.meta.env.DEV is true (see
// api.ts listEvents). In a production build `import.meta.env.DEV` is a
// compile-time false, so this whole module is tree-shaken out of the bundle
// — it can never fake events on the live site, only populate an offline
// dev/preview run so the spotlight, feed, and scroll can be exercised.
import type { Weyn } from "./api";

function iso(dayOffset: number, hour: number, min = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
}

type Seed = Omit<Weyn, "endsAt" | "cancelled" | "ticketingType" | "externalTicketUrl" | "organizerContact"> &
  Partial<Pick<Weyn, "endsAt" | "featured">>;

const RAW: Seed[] = [
  { id: "dev-street-food", title: "Mutrah Night Food Market", organizer: "Mutrah Collective", cat: "food", startsAt: iso(0, 18), venue: "Mutrah Corniche", area: "Mutrah", lat: 23.62, lng: 58.57, distanceKm: 4.8, price: 0, capacity: 999, sold: 240, image: null, color: "#B5562F", glyph: "🍢", blurb: "Twenty stalls along the water — shawarma, grilled hammour, karak, and Omani halwa.", tags: ["outdoor", "family-friendly"], refundPolicy: "Free entry", minAge: 0, featured: true },
  { id: "dev-indie", title: "Desert Sessions: Live", organizer: "Wadi Sound", cat: "music", startsAt: iso(8, 20), venue: "Amphitheatre, Al Mouj", area: "Al Mouj", lat: 23.61, lng: 58.28, distanceKm: 3.6, price: 20, capacity: 1200, sold: 940, image: null, color: "#3E2B54", glyph: "🎸", blurb: "Three indie acts under the open sky. Food trucks from 6pm.", tags: ["outdoor", "16+"], refundPolicy: "Refund up to 7 days before", minAge: 16, featured: true },
  { id: "dev-food-fest", title: "Muscat Food Festival 2026", organizer: "Visit Muscat", cat: "food", startsAt: iso(12, 15), venue: "Al Amerat Park", area: "Al Amerat", lat: 23.52, lng: 58.50, distanceKm: 14, price: 3, capacity: 5000, sold: 1180, image: null, color: "#8A4B2B", glyph: "🍽", blurb: "Three days, eighty vendors, a chef stage, and a kids' zone.", tags: ["family-friendly", "weekend"], refundPolicy: "Refund up to 7 days before", minAge: 0, featured: true },
  { id: "dev-marathon", title: "Corniche Half Marathon", organizer: "Run Oman", cat: "sports", startsAt: iso(10, 5, 30), venue: "Mutrah Corniche start line", area: "Mutrah", lat: 23.62, lng: 58.57, distanceKm: 4.9, price: 8, capacity: 2000, sold: 1320, image: null, color: "#1F5E63", glyph: "🏃", blurb: "21km along the water before the heat. Chip timing, finisher medal.", tags: ["outdoor", "registration"], refundPolicy: "No refunds", minAge: 16, featured: true },
  { id: "dev-boxing", title: "Muscat Fight Night III", organizer: "Gulf Combat Club", cat: "sports", startsAt: iso(0, 20), venue: "Al Mouj Arena", area: "Al Mouj", lat: 23.61, lng: 58.28, distanceKm: 3.4, price: 12, capacity: 400, sold: 362, image: null, color: "#2A2E45", glyph: "🥊", blurb: "Eight amateur bouts, a title fight, and the loudest crowd in the city.", tags: ["18+", "indoor"], refundPolicy: "No refunds within 24h", minAge: 16 },
  { id: "dev-oud", title: "Oud & Coffee on the Roof", organizer: "Bait Al Zubair", cat: "music", startsAt: iso(0, 21, 30), venue: "Old Muscat rooftop", area: "Old Muscat", lat: 23.61, lng: 58.59, distanceKm: 6.1, price: 5, capacity: 60, sold: 48, image: null, color: "#2F5D52", glyph: "🎶", blurb: "Live oud under the stars with cardamom coffee and dates.", tags: ["acoustic", "outdoor"], refundPolicy: "Refund up to 48h before", minAge: 0 },
  { id: "dev-jazz", title: "Jazz Supper Club", organizer: "The Cellar", cat: "music", startsAt: iso(1, 22), venue: "The Cellar, Shatti", area: "Shatti Al Qurum", lat: 23.61, lng: 58.48, distanceKm: 2.2, price: 9, capacity: 50, sold: 44, image: null, color: "#2C3350", glyph: "🎷", blurb: "A trio, low light, and a short menu. Late seating only.", tags: ["indoor", "21+"], refundPolicy: "No refunds", minAge: 21 },
  { id: "dev-pottery", title: "Beginner Pottery Wheel", organizer: "Clay House Studio", cat: "workshop", startsAt: iso(1, 11), venue: "Clay House, Azaiba", area: "Azaiba", lat: 23.59, lng: 58.42, distanceKm: 7.2, price: 18, capacity: 10, sold: 6, image: null, color: "#7A5230", glyph: "🏺", blurb: "Two hours on the wheel, all clay and tools included.", tags: ["beginner", "indoor"], refundPolicy: "Refund up to 24h before", minAge: 12 },
  { id: "dev-car", title: "Friday JDM Car Meet", organizer: "Muscat Auto Scene", cat: "community", startsAt: iso(3, 18, 30), venue: "Qurum Beach car park", area: "Qurum", lat: 23.61, lng: 58.48, distanceKm: 5, price: 0, capacity: 999, sold: 130, image: null, color: "#3A4668", glyph: "🚗", blurb: "Skylines, Supras, and a few surprises. Coffee truck on site.", tags: ["outdoor", "free"], refundPolicy: "Free entry", minAge: 0 },
  { id: "dev-uni", title: "SQU Spring Culture Fest", organizer: "SQU Student Union", cat: "culture", startsAt: iso(6, 16), venue: "Sultan Qaboos University", area: "Al Khoudh", lat: 23.59, lng: 58.17, distanceKm: 11.3, price: 2, capacity: 800, sold: 210, image: null, color: "#6B3F5B", glyph: "🎏", blurb: "Food from twelve countries, a poetry stage, henna, and a night market.", tags: ["family-friendly", "outdoor"], refundPolicy: "Refund up to 7 days before", minAge: 0 },
  { id: "dev-beach", title: "Sunrise Beach Cleanup + Yoga", organizer: "Green Muscat", cat: "community", startsAt: iso(5, 6), venue: "Yiti Beach", area: "Yiti", lat: 23.54, lng: 58.65, distanceKm: 18.4, price: 0, capacity: 80, sold: 52, image: null, color: "#4A6B52", glyph: "🌅", blurb: "Gloves and bags provided. Stay for a free sunrise yoga flow and karak.", tags: ["outdoor", "wellness"], refundPolicy: "Free entry", minAge: 0 },
  { id: "dev-comedy", title: "Standup Night: Open Mic", organizer: "Muscat Comedy Cellar", cat: "culture", startsAt: iso(2, 21), venue: "The Loft, Ghubra", area: "Al Ghubra", lat: 23.59, lng: 58.44, distanceKm: 6.4, price: 6, capacity: 90, sold: 61, image: null, color: "#514063", glyph: "🎤", blurb: "Ten comics, five minutes each, one very brave headliner.", tags: ["indoor", "18+"], refundPolicy: "No refunds", minAge: 18 },
  { id: "dev-tech", title: "Founders & Coffee Meetup", organizer: "Oman Startup Hub", cat: "workshop", startsAt: iso(4, 9), venue: "Innovation Hub, KOM", area: "Knowledge Oasis", lat: 23.58, lng: 58.28, distanceKm: 12.1, price: 0, capacity: 120, sold: 74, image: null, color: "#2E4A5A", glyph: "☕", blurb: "Casual morning meetup for founders, builders, and the merely curious.", tags: ["networking", "free"], refundPolicy: "Free entry", minAge: 16 },
  { id: "dev-film", title: "Open-Air Film: Classics", organizer: "Reel Muscat", cat: "culture", startsAt: iso(7, 19, 30), venue: "Qurum Natural Park", area: "Qurum", lat: 23.61, lng: 58.49, distanceKm: 5.3, price: 4, capacity: 300, sold: 118, image: null, color: "#3B3252", glyph: "🎬", blurb: "Bring a blanket. A restored classic on a huge inflatable screen under the stars.", tags: ["outdoor", "family-friendly"], refundPolicy: "Refund up to 24h before", minAge: 0 },

  // Extra volume — enough events per day-bucket (today/tomorrow) and enough
  // total count to actually exercise the spotlight carousel, Today/Tomorrow/
  // Near you rails, and the "All events" list at a realistic scale instead
  // of the original ~14-event trickle.
  { id: "dev-sunset-yoga", title: "Sunset Rooftop Yoga", organizer: "Muscat Wellness Collective", cat: "workshop", startsAt: iso(0, 17, 30), venue: "The Terrace, Shatti", area: "Shatti Al Qurum", lat: 23.615, lng: 58.47, distanceKm: 2.6, price: 6, capacity: 30, sold: 21, image: null, color: "#4A6B52", glyph: "🧘", blurb: "All levels. Mats provided, karak after.", tags: ["wellness", "outdoor"], refundPolicy: "Refund up to 24h before", minAge: 12 },
  { id: "dev-quiz-night", title: "Pub Quiz: Movies & Music", organizer: "The Duke's Bar", cat: "community", startsAt: iso(0, 19, 30), venue: "The Duke's Bar, Al Ghubra", area: "Al Ghubra", lat: 23.59, lng: 58.44, distanceKm: 6.7, price: 3, capacity: 60, sold: 40, image: null, color: "#3A4668", glyph: "🧠", blurb: "Teams of up to six. Winner takes the bar tab.", tags: ["indoor", "18+"], refundPolicy: "No refunds", minAge: 18 },
  { id: "dev-street-art", title: "Live Mural Painting", organizer: "Wall Muscat", cat: "culture", startsAt: iso(0, 16), venue: "Al Mouj Boardwalk", area: "Al Mouj", lat: 23.612, lng: 58.281, distanceKm: 3.5, price: 0, capacity: 999, sold: 0, image: null, color: "#6B3F5B", glyph: "🎨", blurb: "Watch two local artists finish a 12-metre mural over the afternoon.", tags: ["outdoor", "free", "family-friendly"], refundPolicy: "Free entry", minAge: 0 },
  { id: "dev-padel", title: "Open Padel Night", organizer: "Muscat Padel Club", cat: "sports", startsAt: iso(0, 20), venue: "Qurum Sports Complex", area: "Qurum", lat: 23.605, lng: 58.485, distanceKm: 4.1, price: 5, capacity: 32, sold: 19, image: null, color: "#1F5E63", glyph: "🎾", blurb: "Drop-in doubles, all levels, paddles available to borrow.", tags: ["indoor", "registration"], refundPolicy: "Refund up to 24h before", minAge: 14 },
  { id: "dev-night-market", title: "Qurum Night Souq", organizer: "Muscat Municipality", cat: "community", startsAt: iso(0, 17), venue: "Qurum Natural Park", area: "Qurum", lat: 23.611, lng: 58.489, distanceKm: 5.0, price: 0, capacity: 999, sold: 300, image: null, color: "#3A4668", glyph: "🏮", blurb: "Local crafts, street food, and a small stage of live acts.", tags: ["outdoor", "free", "family-friendly"], refundPolicy: "Free entry", minAge: 0 },
  { id: "dev-brunch-jazz", title: "Sunday Jazz Brunch", organizer: "The Cellar", cat: "music", startsAt: iso(1, 12), venue: "The Cellar, Shatti", area: "Shatti Al Qurum", lat: 23.61, lng: 58.48, distanceKm: 2.2, price: 15, capacity: 70, sold: 58, image: null, color: "#2C3350", glyph: "🎺", blurb: "Live trio, bottomless karak, a set menu.", tags: ["indoor", "family-friendly"], refundPolicy: "Refund up to 48h before", minAge: 0 },
  { id: "dev-kids-science", title: "Kids' Science Saturday", organizer: "Oman Science Centre", cat: "workshop", startsAt: iso(1, 10), venue: "Oman Across Ages Museum", area: "Manah", lat: 22.98, lng: 57.55, distanceKm: 62, price: 4, capacity: 100, sold: 71, image: null, color: "#7A5230", glyph: "🔬", blurb: "Hands-on experiments for ages 6-12. Parents welcome to join in.", tags: ["family-friendly", "indoor"], refundPolicy: "Refund up to 24h before", minAge: 0 },
  { id: "dev-cricket", title: "Friday Night Cricket League", organizer: "Muscat Cricket Council", cat: "sports", startsAt: iso(1, 19), venue: "Al Amerat Ground", area: "Al Amerat", lat: 23.52, lng: 58.50, distanceKm: 14, price: 2, capacity: 500, sold: 210, image: null, color: "#2A2E45", glyph: "🏏", blurb: "Group-stage match night, food stalls pitch-side.", tags: ["outdoor"], refundPolicy: "No refunds", minAge: 0 },
  { id: "dev-cheese-wine", title: "Cheese & Wine Tasting", organizer: "The Cellar Door", cat: "food", startsAt: iso(1, 20), venue: "The Cellar Door, Shatti", area: "Shatti Al Qurum", lat: 23.613, lng: 58.478, distanceKm: 2.4, price: 25, capacity: 24, sold: 22, image: null, color: "#8A4B2B", glyph: "🧀", blurb: "Six pairings, guided by the house sommelier. Limited seats.", tags: ["indoor", "21+"], refundPolicy: "No refunds", minAge: 21 },
  { id: "dev-improv", title: "Improv Comedy Jam", organizer: "Muscat Comedy Cellar", cat: "culture", startsAt: iso(1, 21), venue: "The Loft, Ghubra", area: "Al Ghubra", lat: 23.59, lng: 58.44, distanceKm: 6.4, price: 5, capacity: 90, sold: 30, image: null, color: "#514063", glyph: "🎭", blurb: "Audience-suggested scenes, no script, no safety net.", tags: ["indoor", "16+"], refundPolicy: "No refunds", minAge: 16 },
  { id: "dev-dhow-sunset", title: "Sunset Dhow Cruise", organizer: "Muscat Bay Cruises", cat: "culture", startsAt: iso(2, 17), venue: "Marina Bandar Al Rowdha", area: "Al Rowdha", lat: 23.62, lng: 58.58, distanceKm: 5.7, price: 22, capacity: 40, sold: 33, image: null, color: "#6B3F5B", glyph: "⛵", blurb: "Two hours along the coast, karak and dates included.", tags: ["outdoor", "family-friendly"], refundPolicy: "Refund up to 48h before", minAge: 0 },
  { id: "dev-open-water", title: "Beginner Open-Water Swim", organizer: "Oman Ocean Sports", cat: "sports", startsAt: iso(2, 7), venue: "Bandar Al Khayran", area: "Bandar Khayran", lat: 23.52, lng: 58.68, distanceKm: 16.5, price: 10, capacity: 20, sold: 9, image: null, color: "#1F5E63", glyph: "🏊", blurb: "Coached open-water swim in calm, clear water. Wetsuits available.", tags: ["outdoor", "registration"], refundPolicy: "Refund up to 24h before", minAge: 14 },
  { id: "dev-vinyl-night", title: "Vinyl Night: Disco & Funk", organizer: "Dune Records", cat: "music", startsAt: iso(2, 21, 30), venue: "Dune Records Bar", area: "Al Ghubra", lat: 23.588, lng: 58.443, distanceKm: 6.6, price: 4, capacity: 55, sold: 27, image: null, color: "#3E2B54", glyph: "🕺", blurb: "All-vinyl set, dance floor, low light.", tags: ["indoor", "18+"], refundPolicy: "No refunds", minAge: 18 },
  { id: "dev-tote-bag", title: "Screen-Printing Workshop", organizer: "Ink & Cloth Studio", cat: "workshop", startsAt: iso(3, 15), venue: "Ink & Cloth Studio, Azaiba", area: "Azaiba", lat: 23.592, lng: 58.418, distanceKm: 7.4, price: 14, capacity: 12, sold: 5, image: null, color: "#7A5230", glyph: "🖨", blurb: "Print your own tote bag, three designs to choose from.", tags: ["beginner", "indoor"], refundPolicy: "Refund up to 24h before", minAge: 10 },
  { id: "dev-esports", title: "Muscat Esports Open", organizer: "GG Oman", cat: "community", startsAt: iso(3, 14), venue: "GG Arena, Al Khuwair", area: "Al Khuwair", lat: 23.585, lng: 58.40, distanceKm: 8.9, price: 3, capacity: 200, sold: 96, image: null, color: "#3A4668", glyph: "🎮", blurb: "Open-bracket FIFA and Valorant, spectator seating and a snack bar.", tags: ["indoor", "registration"], refundPolicy: "No refunds", minAge: 12 },
  { id: "dev-poetry", title: "Nabati Poetry Evening", organizer: "Bait Al Zubair", cat: "culture", startsAt: iso(3, 20), venue: "Bait Al Zubair Museum", area: "Old Muscat", lat: 23.611, lng: 58.591, distanceKm: 6.0, price: 3, capacity: 70, sold: 24, image: null, color: "#6B3F5B", glyph: "📜", blurb: "An evening of traditional Nabati verse, with English surtitles.", tags: ["indoor", "family-friendly"], refundPolicy: "Refund up to 24h before", minAge: 0 },
  { id: "dev-crossfit", title: "Charity WOD: Lift for a Cause", organizer: "Iron Dunes CrossFit", cat: "sports", startsAt: iso(4, 7), venue: "Iron Dunes Box, Ghala", area: "Ghala", lat: 23.57, lng: 58.42, distanceKm: 9.6, price: 8, capacity: 60, sold: 41, image: null, color: "#2A2E45", glyph: "🏋", blurb: "All proceeds go to the Children's Cancer Fund. All fitness levels welcome.", tags: ["indoor", "registration"], refundPolicy: "No refunds", minAge: 16 },
  { id: "dev-halwa-class", title: "Omani Halwa Masterclass", organizer: "Bait Al Halwa", cat: "food", startsAt: iso(4, 16, 30), venue: "Bait Al Halwa, Mutrah", area: "Mutrah", lat: 23.618, lng: 58.568, distanceKm: 4.6, price: 12, capacity: 16, sold: 13, image: null, color: "#B5562F", glyph: "🍯", blurb: "Learn the family recipe, take a batch home in a traditional tin.", tags: ["beginner", "indoor", "family-friendly"], refundPolicy: "Refund up to 24h before", minAge: 8 },
  { id: "dev-photo-walk", title: "Old Muscat Photo Walk", organizer: "Frame Oman", cat: "culture", startsAt: iso(5, 16), venue: "Old Muscat Gate", area: "Old Muscat", lat: 23.614, lng: 58.593, distanceKm: 6.3, price: 0, capacity: 25, sold: 18, image: null, color: "#3B3252", glyph: "📷", blurb: "A guided two-hour walk through the old quarter's best light.", tags: ["outdoor", "free"], refundPolicy: "Free entry", minAge: 10 },
  { id: "dev-kite-surf", title: "Kitesurfing Taster Session", organizer: "Barr Al Jissah Kite Co.", cat: "sports", startsAt: iso(6, 8), venue: "Barr Al Jissah Beach", area: "Barr Al Jissah", lat: 23.58, lng: 58.65, distanceKm: 13.2, price: 30, capacity: 8, sold: 3, image: null, color: "#1F5E63", glyph: "🪁", blurb: "One-on-one intro on the water, all gear included.", tags: ["outdoor", "registration"], refundPolicy: "Refund up to 48h before", minAge: 14 },
  { id: "dev-board-games", title: "Board Game Café Night", organizer: "Meeple House", cat: "community", startsAt: iso(6, 18), venue: "Meeple House, Al Khuwair", area: "Al Khuwair", lat: 23.583, lng: 58.402, distanceKm: 8.7, price: 2, capacity: 45, sold: 20, image: null, color: "#3A4668", glyph: "🎲", blurb: "Over sixty titles on the shelf, staff on hand to teach.", tags: ["indoor", "family-friendly"], refundPolicy: "No refunds", minAge: 6 },
];

export function devEvents(): Weyn[] {
  return RAW.map((e) => ({
    endsAt: null,
    cancelled: false,
    ticketingType: "weyn",
    externalTicketUrl: null,
    organizerContact: null,
    ...e,
  })) as Weyn[];
}
